id = "pluto"
name = "Pluto"
description = "Syntax highlighting for the Pluto programming language"
version = "0.1.0"
schema_version = 1
authors = ["Matthew Kerian"]
repository = "https://github.com/matthewkerian/tree-sitter-pluto"

[grammars.pluto]
repository = "https://github.com/matthewkerian/tree-sitter-pluto"
rev = "main"
